export const DAILY_START_TIME = '17:00';
export const DAILY_END_TIME = '22:00';
export const FAVORITE_SUBJECT_PRIORITY_BOOST = 1.5;
export const LOW_PERFORMANCE_BOOST = 1.3;
export const DEFAULT_PASS_COVERAGE = 3;
export const INTERJECTION_INTERVAL = 4;
export const POOR_PERFORMANCE_THRESHOLD = 0.4;